url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "kevin russell moy" # the name of your site, e.g. ACME Corp.
description: "Stanford Ph.D. Candidate in Energy Resources Engineering"
